
title: "Pree"
baseurl: "/pree-static" # the subpath of your site, e.g. /blog
url: "pree.it" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [_site, /assets, /gulp, /node_modules,gulpfile.js,_assets,bower.json,Gemfile ,Gemfile.lock,package.json, webpack.config.js, main.js]

description: "hello mundo!!! "
